- name: pickaxe
  type: tools
  icon: res://material/textures/tools/pickaxe.png
  scene: res://scenes/items/tools/pickaxe.tscn

- name: axe
  type: tools
  icon: res://material/textures/tools/axe.png
  scene: res://scenes/items/tools/axe.tscn
  
- name: sickle
  type: tools
  icon: res://material/textures/tools/sickle.png
  scene: res://scenes/items/tools/sickle.tscn
 
- name: null
  type: null
  sort: null
  icon: null
  scene: null
